const express = require('express');
const cors = require('cors');
const fetch = require('node-fetch');
const path = require('path');
const fs = require('fs');
require('dotenv').config();

const app = express();
const PORT = process.env.PORT || 8080;

// Middleware
app.use(cors());
app.use(express.json());

// Dynamically generate config.js with environment variables
app.get('/config.js', (req, res) => {
  const config = `
    // This file is dynamically generated by the server
    window.ENV_CONFIG = {
      API_ENDPOINT: '/api/ask'
    };
  `;
  res.setHeader('Content-Type', 'application/javascript');
  res.send(config);
});

// Static files middleware
app.use(express.static(path.join(__dirname)));

// API Proxy endpoint
app.post('/api/ask', async (req, res) => {
  try {
    const { query } = req.body;
    console.log('Proxying request to API:', query);

    const apiUrl = process.env.API_ENDPOINT || 'https://odd-disk-7724.ploomber.app/ask';
    
    const response = await fetch(apiUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ query })
    });

    if (!response.ok) {
      throw new Error(`API responded with status: ${response.status}`);
    }

    const data = await response.json();
    res.json(data);
  } catch (error) {
    console.error('Proxy error:', error.message);
    res.status(500).json({ 
      error: 'An error occurred while processing your request',
      response: 'Sorry, I couldn\'t process that request. Please try again later.'
    });
  }
});

// Serve the main HTML file for all other routes
app.get('*', (req, res) => {
  res.sendFile(path.join(__dirname, 'index.html'));
});

// Start server
app.listen(PORT, () => {
  console.log(`Server running on http://localhost:${PORT}`);
}); 