const express = require('express');
const cors = require('cors');
const fetch = require('node-fetch');
const path = require('path');
require('dotenv').config();

const app = express();

// Middleware
app.use(cors());
app.use(express.json());

// Dynamically generate config.js with environment variables
app.get('/config.js', (req, res) => {
  const config = `
    // This file is dynamically generated by the server
    window.ENV_CONFIG = {
      API_ENDPOINT: '/api/ask'
    };
  `;
  res.setHeader('Content-Type', 'application/javascript');
  res.send(config);
});

// Static files middleware - only needed for local development
// On Vercel, static files are handled directly by Vercel
if (process.env.NODE_ENV !== 'production') {
  app.use(express.static(path.join(__dirname)));
}

// API Proxy endpoint
app.post('/api/ask', async (req, res) => {
  try {
    const { query } = req.body;
    console.log('Proxying request to API:', query);

    // Updated API endpoint or use environment variable
    const apiUrl = process.env.API_ENDPOINT || 'https://pho24-chatbot.vercel.app/ask';
    
    console.log('Sending request to:', apiUrl);
    
    const response = await fetch(apiUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ query }),
      redirect: 'follow', // Follow redirects automatically
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('API error response:', errorText);
      throw new Error(`API responded with status: ${response.status}, message: ${errorText.substring(0, 100)}`);
    }

    const data = await response.json();
    console.log('API response:', data);
    res.json(data);
  } catch (error) {
    console.error('Proxy error:', error.message);
    res.status(500).json({ 
      error: 'An error occurred while processing your request',
      response: 'Sorry, I couldn\'t process that request. Please try again later.'
    });
  }
});

// For local development, serve the main HTML file
if (process.env.NODE_ENV !== 'production') {
  app.get('*', (req, res) => {
    res.sendFile(path.join(__dirname, 'index.html'));
  });

  const PORT = process.env.PORT || 8080;
  app.listen(PORT, () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

// Export for Vercel
module.exports = app; 