// Vercel serverless function for the /api/config endpoint
module.exports = (req, res) => {
  // Set content type to JavaScript
  res.setHeader('Content-Type', 'application/javascript');
  
  // Generate the config
  const config = `
    // This file is dynamically generated by the server
    window.ENV_CONFIG = {
      API_ENDPOINT: '/ask'
    };
  `;
  
  // Send the response
  res.status(200).send(config);
}; 